---
name: Django test container
author: Arne Tarara <arne@green-coding.io>
description: Energy measurements of the Django official unit tests

sci:
  R_d: Unit test

services:
  gcb-django-tests:
    image: python:3.13.2-slim-bookworm
    container_name: gcb-django-tests
    setup-commands:
      - command: apt update && apt install -y libmemcached-dev zlib1g-dev gcc
        shell: sh
      - command: pip install --upgrade pip
      - command: mkdir /var/www
      - command: cp -R /tmp/repo /var/www/django # We have to copy the code outside of the read-only mount in /tmp/repo, because django needs to write files.
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: 2


flow:
  - name: Install Django base libraries
    container: gcb-django-tests
    commands:
      - type: console
        command: python -m pip install -e /var/www/django --root-user-action=ignore
        log-stdout: True
        log-stderr: True
        read-sci-stdout: True

  - name: Install Django test libraries
    container: gcb-django-tests
    commands:
      - type: console
        command: python -m pip install -r /var/www/django/tests/requirements/py3.txt --root-user-action=ignore
        log-stdout: True
        log-stderr: True
        read-sci-stdout: True

  - name: Run Django tests
    container: gcb-django-tests
    commands:
      - type: console
        command: python /var/www/django/tests/runtests.py --parallel 2 --noinput | awk '/Found [0-9]+ test\(s\)/ { gsub(/Found | test\(s\)/, "", $0); print "GMT_SCI_R=" $0 }'
        shell: bash
        log-stdout: True
        log-stderr: True
        read-sci-stdout: True
        ignore-errors: True
